/********************************************************************
* /home/schumans/Worker/A2/src/WorkerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/schumans/Worker/A2/src/WorkerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWorkerDict();
extern void G__cpp_setup_inheritanceWorkerDict();
extern void G__cpp_setup_typetableWorkerDict();
extern void G__cpp_setup_memvarWorkerDict();
extern void G__cpp_setup_globalWorkerDict();
extern void G__cpp_setup_memfuncWorkerDict();
extern void G__cpp_setup_funcWorkerDict();
extern void G__set_cpp_environmentWorkerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/schumans/Worker/A2/src/TProcessor.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WorkerDictLN_TClass;
extern G__linked_taginfo G__WorkerDictLN_TBuffer;
extern G__linked_taginfo G__WorkerDictLN_TMemberInspector;
extern G__linked_taginfo G__WorkerDictLN_TObject;
extern G__linked_taginfo G__WorkerDictLN_TNamed;
extern G__linked_taginfo G__WorkerDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__WorkerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WorkerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WorkerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WorkerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WorkerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WorkerDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__WorkerDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WorkerDictLN_TProcessor;

/* STUB derived class for protected member access */
