void AlignTDC(Char_t* taggfile, Int_t xlow = 0.0, Int_t xhigh = 0.0, Int_t switch = 0 )
{
// From a detector file find the "Element:" lines and identify the TDCs used
// for the detector elements. Find the peak position and write this in as TDC offset
// in a new file copied from the original
//
  Char_t taggmod[128];                                // new file to create
  Char_t line[256];                                   // input line from file
  Char_t desc[32];                                    // general purpose char string
  Char_t* p[16];                                      // parameters read from line
  for(Int_t i=0; i<16; i++) p[i] = new Char_t[16];

  strcpy(taggmod, taggfile);                          // copy file of xxx = xxx.align
  strcat(taggmod,".align_dave");
  TH1F* hist;                                         // TDC spectrum
  TF1* gaus;                                          // fit to TDC spectrum
  TAxis* xaxis;                                       // x-axis
  Double_t mean;                                      // mean value of TDC spectrum
  FILE* tfile;                                        // original file pointer
  FILE* mfile;                                        // copy file pointer

  // Open original and copy files
  printf("Aligning TDC spectra found in  %s\n",taggfile);
  if( (tfile = fopen(taggfile,"r")) == NULL ){        // open original read only
    printf("File %s open failed\n",taggfile);
    return;
  }
  if( (mfile = fopen(taggmod,"w")) == NULL ){         // open copy file for write
    printf("File %s open failed\n",taggmod);
    return;
  }
  // Message at top of auto-generated file
  fprintf(mfile,"##     Aligned-TDC AcquRoot Detector file\n");
  fprintf(mfile,"##     Generated by macro AlignTDC.C, J.R.M. Annand, 28th March 2007\n");
  // Read lines from original until EOF
  while( fgets( line, 256, tfile ) ){
    sscanf( line, "%s", desc );                      // get line descriptor
    if( !strcmp( desc, "Element:") ){                // and check if its an element line
      Int_t n = sscanf( line,"%*s%s%s%s%s%s%s%s%s",p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7]);
      n += sscanf( line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%s%s%s%s%s%s%s%s",
		   p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
      if( n != 16){
	printf("Bad file format\n%s\n",line);
	return;
      }
      strcpy(desc,"ADC");                           // pull out the TDC spec
      strcat(desc,p[5]);
      hist = (TH1F*)gROOT->FindObject(desc);        // and search for the TDC histogram
      if( !hist ){
	printf( "%s not found\n", desc );
	return;
      }
      printf("Low = %d, High = %d\n",xlow,xhigh);
      if( xlow || xhigh ){
	xaxis = (TAxis)hist->GetXaxis();             
	xaxis->SetRange(xlow, xhigh);                 // restrict the range if specified
      }
      if( switch){
	hist->Fit("gaus");
	gaus = hist->GetFunction("gaus");
	mean = gaus->GetParameter(1);
      }
      else mean = hist->GetMean();                       // get the mean value
      sprintf( p[8],"%d",mean+300 );
      printf("Mean channel of %s is %d\n",desc,mean); // progress message
      fprintf(mfile,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n", "Element:",
	      p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],
	      p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
    }
    else fputs( line, mfile );    // if not an element line copy it to new file
  }
  // delete any allocated memory and close input and output files 
  for(Int_t i=0; i<16; i++) delete p[i];  
  fclose(tfile);
  fclose(mfile);
  
  return;
}
//                                           
