void LadderNewCal(Char_t* taggfile = NULL, Char_t* calfile = NULL,
		  Double_t eBeam = -1. )
{
// From a detector file find the "Element:" lines
// Replace the electron energy specified there by the value read from a file.
// 1st check for proper set in input variables
//
// J.R.M. Annand 29th September 2007
//
  if( eBeam == -1. ){
    printf(" Change the electron energy calibration of a tagger detector file\n\
 Usage...\n\
 LadderNewCal(Char_t* taggfile, Char_t* calfile, Double_t eBeam)\n\
  taggfile is the name of the original tagger detector file\n\
  calfile is the name of the new calibration table (photon energies specified)\n\
  eBeam is the value of the electron beam energy\n\n");
    return;
  }
  Char_t taggmod[128];                                // new file to create
  Char_t line[256];                                   // input line from file
  Char_t desc[32];                                    // general purpose char string

  strcpy(taggmod, taggfile);                          // copy file of xxx = xxx.align
  strcat(taggmod,".newcal");
  TH1F* hist;                                         // TDC spectrum
  TF1* gaus;                                          // fit to TDC spectrum
  TAxis* xaxis;                                       // x-axis
  Double_t mean;                                      // mean value of TDC spectrum
  FILE* tfile;                                        // original file pointer
  FILE* mfile;                                        // copy file pointer
  FILE* cfile;                                        // copy file pointer
  Double_t goosey, eCal, eWidth;

  // Open original and copy files
  printf(" Modifying electron energy calibration found in: %s\n",taggfile);
  if( (tfile = fopen(taggfile,"r")) == NULL ){        // open original read only
    printf("File %s open failed\n",taggfile);
    return;
  }
  if( (mfile = fopen(taggmod,"w")) == NULL ){         // open copy file for write
    printf("File %s open failed\n",taggmod);
    return;
  }
  if( (cfile = fopen(calfile,"r")) == NULL ){         // open copy file for write
    printf("File %s open failed\n",calfile);
    return;
  }
  // Message at top of auto-generated file
  fprintf(mfile,"##     Ladder file with recalibration of electron energies\n");
  fprintf(mfile,"##     Generated by macro LadderNewCal.C, J.R.M. Annand, 29th September 2007\n");
  // Read lines from original until EOF
  Int_t i = 0;
  Char_t* p[16];                            // parameters read from line
  for(Int_t j=0; j<16; j++) p[j] = new Char_t[16];
  while( fgets( line, 256, tfile ) ){
    sscanf( line, "%s", desc );             // get line descriptor
    if( !strcmp( desc, "Element:") ){       // and check if its an element line
      Int_t n = sscanf( line,"%*s%s%s%s%s%s%s%s%s",p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7]);
      n += sscanf( line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%s%s%s%s%s%s%s%s",
		   p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
      if( n != 16){
	printf("Bad file format\n%s\n",line);
	return;
      }
      i++;
      fscanf( cfile, "%lf%lf%lf", &goosey, &eCal, &eWidth );
      if( (Int_t)goosey != i ){
	printf(" Data out of synch in calibration file %s %d %d\n",
	       calfile, goosey, i );
	return;
      }

      sprintf( p[13],"%.1f", (eBeam-eCal) );
      sprintf( p[14],"%.1f", eWidth );
      fprintf(mfile,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n", "Element:",
	      p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],
	      p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
    }
    else fputs( line, mfile );    // if not an element line copy it to new file
  }
  // delete any allocated memory and close input and output files 
  for(Int_t i=0; i<16; i++) delete p[i];  
  fclose(tfile);
  fclose(mfile);
  fclose(cfile);
  printf(" New electron-hits calibration written to file:  %s\n\n", taggmod);
  return;
}
//                                           
