/********************************************************************
* /home/acqu/4v6/acqu/AcquRoot/src/AcquRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/acqu/4v6/acqu/AcquRoot/src/AcquRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAcquRootDict();
extern void G__cpp_setup_inheritanceAcquRootDict();
extern void G__cpp_setup_typetableAcquRootDict();
extern void G__cpp_setup_memvarAcquRootDict();
extern void G__cpp_setup_globalAcquRootDict();
extern void G__cpp_setup_memfuncAcquRootDict();
extern void G__cpp_setup_funcAcquRootDict();
extern void G__set_cpp_environmentAcquRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2System.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2HistManager.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2DataManager.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Control.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TAcquRoot.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Analysis.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Physics.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2GenericPhysics.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Apparatus.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2GenericApparatus.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2TOFApparatus.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Tagger.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Detector.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2GenericDetector.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2ClusterDetector.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2LongScint.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Ladder.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2GenericCluster.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2WireChamber.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2H.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Cut.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2MultiCut.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Track.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2WCLayer.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2CylWire.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2CylStrip.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2BitPattern.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2RateMonitor.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2ParticleID.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Particle.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2RingBuffer.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2DataServer.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2DataSource.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2NetSource.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2FileSource.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2LocalSource.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2DataFormat.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Mk1Format.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2Mk2Format.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/TA2TAPSFormat.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/HitD2A_t.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/LongBar_t.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/HitCluster_t.h"
#include "/home/acqu/4v6/acqu/AcquRoot/src/GenHitCluster_t.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AcquRootDictLN_TClass;
extern G__linked_taginfo G__AcquRootDictLN_TBuffer;
extern G__linked_taginfo G__AcquRootDictLN_TMemberInspector;
extern G__linked_taginfo G__AcquRootDictLN_TObject;
extern G__linked_taginfo G__AcquRootDictLN_TNamed;
extern G__linked_taginfo G__AcquRootDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__AcquRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AcquRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AcquRootDictLN_TList;
extern G__linked_taginfo G__AcquRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AcquRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AcquRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AcquRootDictLN_TFile;
extern G__linked_taginfo G__AcquRootDictLN_TApplication;
extern G__linked_taginfo G__AcquRootDictLN_Map_t;
extern G__linked_taginfo G__AcquRootDictLN_ARFile_t;
extern G__linked_taginfo G__AcquRootDictLN_ARSocket_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2System;
extern G__linked_taginfo G__AcquRootDictLN_TTree;
extern G__linked_taginfo G__AcquRootDictLN_TBranch;
extern G__linked_taginfo G__AcquRootDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__AcquRootDictLN_TThread;
extern G__linked_taginfo G__AcquRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__AcquRootDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AcquRootDictLN_TQObject;
extern G__linked_taginfo G__AcquRootDictLN_AcquExptInfo_t;
extern G__linked_taginfo G__AcquRootDictLN_ADCInfo_t;
extern G__linked_taginfo G__AcquRootDictLN_ModuleInfo_t;
extern G__linked_taginfo G__AcquRootDictLN_AcquBlock_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2RingBuffer;
extern G__linked_taginfo G__AcquRootDictLN_TA2DataFormat;
extern G__linked_taginfo G__AcquRootDictLN_AcquMk2Info_t;
extern G__linked_taginfo G__AcquRootDictLN_ModuleInfoMk2_t;
extern G__linked_taginfo G__AcquRootDictLN_ReadErrorMk2_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2Mk2Format;
extern G__linked_taginfo G__AcquRootDictLN_MultiADC_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2Analysis;
extern G__linked_taginfo G__AcquRootDictLN_TA2DataServer;
extern G__linked_taginfo G__AcquRootDictLN_TAcquRoot;
extern G__linked_taginfo G__AcquRootDictLN_TA2Cut;
extern G__linked_taginfo G__AcquRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AcquRootDictLN_TH1F;
extern G__linked_taginfo G__AcquRootDictLN_TF1;
extern G__linked_taginfo G__AcquRootDictLN_TA2MultiCut;
extern G__linked_taginfo G__AcquRootDictLN_TA2BitPattern;
extern G__linked_taginfo G__AcquRootDictLN_TA2RateMonitor;
extern G__linked_taginfo G__AcquRootDictLN_TRandom;
extern G__linked_taginfo G__AcquRootDictLN_TA2DataManager;
extern G__linked_taginfo G__AcquRootDictLN_TA2H;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__AcquRootDictLN_TH2F;
extern G__linked_taginfo G__AcquRootDictLN_TA2HistManager;
extern G__linked_taginfo G__AcquRootDictLN_TRint;
extern G__linked_taginfo G__AcquRootDictLN_TDAQexperiment;
extern G__linked_taginfo G__AcquRootDictLN_TA2Control;
extern G__linked_taginfo G__AcquRootDictLN_FlashADC_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2Detector;
extern G__linked_taginfo G__AcquRootDictLN_HitD2A_t;
extern G__linked_taginfo G__AcquRootDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__AcquRootDictLN_TVector3;
extern G__linked_taginfo G__AcquRootDictLN_TLorentzVector;
extern G__linked_taginfo G__AcquRootDictLN_TParticlePDG;
extern G__linked_taginfo G__AcquRootDictLN_TDatabasePDG;
extern G__linked_taginfo G__AcquRootDictLN_TA2ParticleID;
extern G__linked_taginfo G__AcquRootDictLN_TA2Particle;
extern G__linked_taginfo G__AcquRootDictLN_TA2Apparatus;
extern G__linked_taginfo G__AcquRootDictLN_TA2Physics;
extern G__linked_taginfo G__AcquRootDictLN_TA2GenericPhysics;
extern G__linked_taginfo G__AcquRootDictLN_TA2GenericApparatus;
extern G__linked_taginfo G__AcquRootDictLN_TA2GenericDetector;
extern G__linked_taginfo G__AcquRootDictLN_TA2LongScint;
extern G__linked_taginfo G__AcquRootDictLN_LongBar_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2GenericCluster;
extern G__linked_taginfo G__AcquRootDictLN_GenHitCluster_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2Ladder;
extern G__linked_taginfo G__AcquRootDictLN_TA2TOFApparatus;
extern G__linked_taginfo G__AcquRootDictLN_TA2ClusterDetector;
extern G__linked_taginfo G__AcquRootDictLN_HitCluster_t;
extern G__linked_taginfo G__AcquRootDictLN_TA2Tagger;
extern G__linked_taginfo G__AcquRootDictLN_TA2WCLayer;
extern G__linked_taginfo G__AcquRootDictLN_TA2CylWire;
extern G__linked_taginfo G__AcquRootDictLN_TA2CylStrip;
extern G__linked_taginfo G__AcquRootDictLN_TA2Track;
extern G__linked_taginfo G__AcquRootDictLN_TA2WireChamber;
extern G__linked_taginfo G__AcquRootDictLN_TA2DataSource;
extern G__linked_taginfo G__AcquRootDictLN_TA2NetSource;
extern G__linked_taginfo G__AcquRootDictLN_TA2FileSource;
extern G__linked_taginfo G__AcquRootDictLN_TA2LocalSource;
extern G__linked_taginfo G__AcquRootDictLN_TA2Mk1Format;
extern G__linked_taginfo G__AcquRootDictLN_TA2TAPSFormat;

/* STUB derived class for protected member access */
