/********************************************************************
* /home/acqu/4v6/acqu/AcquMC/src/MCDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/acqu/4v6/acqu/AcquMC/src/MCDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMCDict();
extern void G__cpp_setup_inheritanceMCDict();
extern void G__cpp_setup_typetableMCDict();
extern void G__cpp_setup_memvarMCDict();
extern void G__cpp_setup_globalMCDict();
extern void G__cpp_setup_memfuncMCDict();
extern void G__cpp_setup_funcMCDict();
extern void G__set_cpp_environmentMCDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCResonance.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCPhotoPSInt.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCFoamParticle.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCdS5MDMInt.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCPhotoPSGenerator.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCFoamGenerator.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCFoamInt.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCDgpInt.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCGenerator.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCdS5MDMParticle.h"
#include "/home/acqu/4v6/acqu/AcquMC/src/TMCParticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MCDictLN_TClass;
extern G__linked_taginfo G__MCDictLN_TBuffer;
extern G__linked_taginfo G__MCDictLN_TMemberInspector;
extern G__linked_taginfo G__MCDictLN_TObject;
extern G__linked_taginfo G__MCDictLN_TNamed;
extern G__linked_taginfo G__MCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCDictLN_TList;
extern G__linked_taginfo G__MCDictLN_TClonesArray;
extern G__linked_taginfo G__MCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MCDictLN_TF1;
extern G__linked_taginfo G__MCDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MCDictLN_TH1D;
extern G__linked_taginfo G__MCDictLN_TParticlePDG;
extern G__linked_taginfo G__MCDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MCDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MCDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MCDictLN_TVector3;
extern G__linked_taginfo G__MCDictLN_TLorentzRotation;
extern G__linked_taginfo G__MCDictLN_TLorentzVector;
extern G__linked_taginfo G__MCDictLN_TRandom;
extern G__linked_taginfo G__MCDictLN_TMCParticle;
extern G__linked_taginfo G__MCDictLN_TMCResonance;
extern G__linked_taginfo G__MCDictLN_TFoamIntegrand;
extern G__linked_taginfo G__MCDictLN_TFile;
extern G__linked_taginfo G__MCDictLN_TA2System;
extern G__linked_taginfo G__MCDictLN_TMCFoamInt;
extern G__linked_taginfo G__MCDictLN_TMCPhotoPSInt;
extern G__linked_taginfo G__MCDictLN_TFoam;
extern G__linked_taginfo G__MCDictLN_TMCFoamParticle;
extern G__linked_taginfo G__MCDictLN_TMCdS5MDMInt;
extern G__linked_taginfo G__MCDictLN_TDatabasePDG;
extern G__linked_taginfo G__MCDictLN_TTree;
extern G__linked_taginfo G__MCDictLN_TBranch;
extern G__linked_taginfo G__MCDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MCDictLN_TNtuple;
extern G__linked_taginfo G__MCDictLN_TMCdS5MDMParticle;
extern G__linked_taginfo G__MCDictLN_TMCGenerator;
extern G__linked_taginfo G__MCDictLN_TMCDgpInt;
extern G__linked_taginfo G__MCDictLN_TMCFoamGenerator;
extern G__linked_taginfo G__MCDictLN_TMCPhotoPSGenerator;

/* STUB derived class for protected member access */
