void LadderNewPos(Char_t* laddfile = NULL, Char_t* posfile = NULL )
{
// From a detector file find the "Element:" lines
// Replace the electron energy specified there by the value read from a file.
// 1st check for proper set in input variables
//
// J.R.M. Annand 29th September 2007
//
  Char_t taggmod[256];                                // new file to create
  Char_t line[256];                                   // input line from file
  Char_t desc[32];                                    // general purpose char string

  strcpy(taggmod, laddfile);                          // copy file of xxx = xxx.align
  strcat(taggmod,".newpos");
  TH1F* hist;                                         // TDC spectrum
  TF1* gaus;                                          // fit to TDC spectrum
  TAxis* xaxis;                                       // x-axis
  Double_t mean;                                      // mean value of TDC spectrum
  FILE* tfile;                                        // original file pointer
  FILE* mfile;                                        // copy file pointer
  FILE* cfile;                                        // copy file pointer
  Double_t x,y,z;

  // Open original and copy files
  printf(" Modifying position calibration found in: %s\n",laddfile);
  if( (tfile = fopen(laddfile,"r")) == NULL ){        // open original read only
    printf("File %s open failed\n",laddfile);
    return;
  }
  if( (mfile = fopen(taggmod,"w")) == NULL ){         // open copy file for write
    printf("File %s open failed\n",taggmod);
    return;
  }
  if( (cfile = fopen(posfile,"r")) == NULL ){         // open copy file for write
    printf("File %s open failed\n",posfile);
    return;
  }
  // Message at top of auto-generated file
  fprintf(mfile,"##     Ladder file with recalibration of positions\n");
  fprintf(mfile,"##     Generated by macro LadderNewPos.C, J.R.M. Annand, 16th September 2008\n");
  // Read lines from original until EOF
  Int_t i = 0;
  Char_t* p[16];                            // parameters read from line
  for(Int_t j=0; j<16; j++) p[j] = new Char_t[16];
  while( fgets( line, 256, tfile ) ){
    sscanf( line, "%s", desc );             // get line descriptor
    if( !strcmp( desc, "Element:") ){       // and check if its an element line
      Int_t n = sscanf( line,"%*s%s%s%s%s%s%s%s%s",p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7]);
      n += sscanf( line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%s%s%s%s%s%s%s%s",
		   p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
      printf("%s\n",line);
      printf("%d  %d\n",i,n);
      switch (n){
      case 13:
	strcpy(p[13],"");
      case 14:
	strcpy(p[14],"");
      case 15:
	strcpy(p[15],"");
      case 16:
	break;
      default:
	printf("Bad file format\n%s\n",line);
	return;
      }
      i++;
      fscanf( cfile, "%lf%lf%lf", &x, &y, &z );
      printf("%f %f %f\n",x,y,z);

      sprintf( p[10],"%.1f", x );
      sprintf( p[11],"%.1f", y );
      sprintf( p[12],"%.1f", z );
      fprintf(mfile,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n",
	      "Element:",
	      p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],
	      p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
    }
    else fputs( line, mfile );    // if not an element line copy it to new file
  }
  printf(" New hits position written to file:  %s\n\n", taggmod);
  // delete any allocated memory and close input and output files 
  for(Int_t i=0; i<16; i++) delete p[i];  
  fclose(tfile);
  fclose(mfile);
  fclose(cfile);
}
