void LadderNewCal(Char_t* taggfile = NULL, Char_t* calfile = NULL,
		  Double_t eBeam = -1. )
{
// From a detector file find the "Element:" lines
// Replace the electron energy specified there by the value read from a file.
// 1st check for proper set in input variables
//
// J.R.M. Annand 29th September 2007
// J.R.M. Annand  9th November  2008 
// Added output to 2 variable-width histogram files
// 1st has no tagger-channel overlap info...edge is middle of overlap region
// 2nd includes overlap regions as separate bins
//
  if( eBeam == -1. ){
    printf(" Change the electron energy calibration of a tagger detector file\n\
 Usage...\n\
 LadderNewCal(Char_t* taggfile, Char_t* calfile, Double_t eBeam)\n\
  taggfile is the name of the original tagger detector file\n\
  calfile is the name of the new calibration table (photon energies specified)\n\
  eBeam is the value of the electron beam energy\n\n");
    return;
  }
  Char_t taggmod[256];                     // new file to create
  Char_t ehist[256];                       // name of electron hist file
  Char_t ehistd[256];                      // electron hist file with doubles
  Char_t ghist[256];                       // name of gamma hist file
  Char_t ghistd[256];                      // gamma hist file with doubles
  Char_t line[256];                        // input line from file
  Char_t desc[32];                         // general purpose char string
  Double_t hlim[2048];                     // hist bin delimiters
  Double_t hlimd[2048];                    // hist bin delim with overlap

  strcpy(taggmod, taggfile);               // config file of taggmod.newcal
  strcat(taggmod,".newcal");
  strcpy(ehist, calfile);                  // axis bins file calfile.ehist
  strcat(ehist,".ehist");
  strcpy(ehistd, calfile);                 // axis bins file calfile.ehistd
  strcat(ehistd,".ehistd");
  strcpy(ghist, calfile);                  // axis bins file calfile.ehist
  strcat(ghist,".ghist");
  strcpy(ghistd, calfile);                 // axis bins file calfile.ehistd
  strcat(ghistd,".ghistd");
  TH1F* hist;                              // TDC spectrum
  TF1* gaus;                               // fit to TDC spectrum
  TAxis* xaxis;                            // x-axis
  Double_t mean;                           // mean value of TDC spectrum
  FILE* tfile;                             // original file pointer
  FILE* mfile;                             // newcal file pointer
  FILE* cfile;                             // calib file pointer
  FILE* efile;                             // ehist file pointer
  FILE* efiled;                            // ehistd file pointer
  FILE* gfile;                             // ghist file pointer
  FILE* gfiled;                            // ghistd file pointer
  Double_t goosey, eCal, eWidth, eL0, eL1, eH0, eH1;

  // Open original and copy files
  // Print autogen message on copy files
  //
  printf(" Modifying electron energy calibration found in: %s\n",taggfile);
  if( (tfile = fopen(taggfile,"r")) == NULL ){     // open original read only
    printf("File %s open failed\n",taggfile);
    return;
  }
  if( (mfile = fopen(taggmod,"w")) == NULL ){      // open newcal file for write
    printf("File %s open failed\n",taggmod);
    return;
  }
  fprintf(mfile,"##     Ladder file with recalibration of electron energies\n");
  fprintf(mfile,"##     Generated by macro LadderNewCal.C, J.R.M. Annand, 11th November 2008\n");
  //
  if( (cfile = fopen(calfile,"r")) == NULL ){      // open calib read only
    printf("File %s open failed\n",calfile);
    return;
  }
  //
  if( (efile = fopen(ehist,"w")) == NULL ){     // open hist file for write
    printf("File %s open failed\n",ehist);
    return;
  }
  fprintf(efile,"##     Electron histogram bin file without overlaps\n");
  fprintf(efile,"##     Generated by macro LadderNewCal.C, J.R.M. Annand, 11th November 2008\n");
  //
  if( (efiled = fopen(ehistd,"w")) == NULL ){   // open histd file for write
    printf("File %s open failed\n",ehistd);
    return;
  }
  fprintf(efiled,"##     Electron histogram bin file with overlaps\n");
  fprintf(efiled,"##     Generated by macro LadderNewCal.C, J.R.M. Annand, 11th November 2008\n");
  //
  if( (gfile = fopen(ghist,"w")) == NULL ){     // open hist file for write
    printf("File %s open failed\n",ehist);
    return;
  }
  fprintf(gfile,"##     Gamma histogram bin file without overlaps\n");
  fprintf(gfile,"##     Generated by macro LadderNewCal.C, J.R.M. Annand, 11th November 2008\n");
  //
  if( (gfiled = fopen(ghistd,"w")) == NULL ){   // open histd file for write
    printf("File %s open failed\n",ehistd);
    return;
  }
  fprintf(gfiled,"##     Gamma histogram bin file with overlaps\n");
  fprintf(gfiled,"##     Generated by macro LadderNewCal.C, J.R.M. Annand, 11th November 2008\n");
  //
  Int_t i = 0;
  Char_t* p[16];                            // parameters read from line
  Int_t k = 0;
  for(Int_t j=0; j<16; j++) p[j] = new Char_t[16];
  while( fgets( line, 256, tfile ) ){
    sscanf( line, "%s", desc );             // get line descriptor
    // Read the line in 2 chunks (CINT limitations)
    if( !strcmp( desc, "Element:") ){       // and check if its an element line
      Int_t n = sscanf( line,"%*s%s%s%s%s%s%s%s%s",p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7]);
      n += sscanf( line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%s%s%s%s%s%s%s%s",
		   p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
      if( n != 16){
	printf("Bad file format\n%s\n",line);
	return;
      }
      printf("%s\n", line);
      i++;
      // read the associated calibration info
      fscanf( cfile, "%lf%lf%lf", &goosey, &eCal, &eWidth );
      if( (Int_t)goosey != i ){
	printf(" Data out of synch in calibration file %s %d %d\n",
	       calfile, goosey, i );
	return;
      }
      printf("%f %f %f\n", goosey, eCal, eWidth);

      sprintf( p[13],"%.3f", (eBeam-eCal) );
      sprintf( p[14],"%.3f", eWidth );
      fprintf(mfile,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n", "Element:",
	      p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],
	      p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
      if( i == 1 ){
	eL0 = eCal - 0.5*eWidth;
	eH0 = eCal + 0.5*eWidth;
	hlim[i-1] = eH0;
	hlimd[k] = eH0;
	k++;
      }
      else{
	eL1 = eCal - 0.5*eWidth;
	eH1 = eCal + 0.5*eWidth;
	if( eH1 > eL0 ){
	  hlimd[k] = eH1;
	  k++;
	  hlimd[k] = eL0;
	  k++;
	}
	else{
	  hlimd[k] = eL0;
	  k++;
	}
	hlim[i-1] = 0.5*(eL0 + eH1);
	eL0 = eL1;
	eH0 = eH1;
      }
    }
    else fputs( line, mfile );    // if not an element line copy it to new file
  }
  hlim[i] = eL1;
  hlimd[k] = eL1;
  for( Int_t j=0; j<=i; j++ )fprintf(efile,"%4d %.3f\n", j,eBeam-hlim[j] );
  for( Int_t j=i; j>=0; j-- )fprintf(gfile,"%4d %.3f\n", i-j,hlim[j] );
  for( Int_t j=0; j<=k; j++ )fprintf(efiled,"%4d %.3f\n", j,eBeam-hlimd[j] );
  for( Int_t j=k; j>=0; j-- )fprintf(gfiled,"%4d %.3f\n", k-j,hlimd[j] );
  //
  // delete any allocated memory and close input and output files 
  for(Int_t i=0; i<16; i++) delete p[i];  
  fclose(tfile);
  fclose(mfile);
  fclose(cfile);
  fclose(efile);
  fclose(efiled);
  fclose(gfile);
  fclose(gfiled);
  printf("\n");
  printf(" Electron-hits calibration written to ladder file:\n  %s\n", taggmod);
  printf(" Electron-energy histogram bin limits (no overlap) in file:\n  %s\n",
	 ehist);
  printf(" Electron-energy histogram bin limits (with overlap) in file:\n  %s\n",
	 ehistd);
  printf(" Photon-energy histogram bin limits (no overlap) in file:\n  %s\n",
	 ghist);
  printf(" Photon-energy histogram bin limits (with overlap) in file:\n  %s\n",
	 ghistd);
  return;
}
//                                           
