/********************************************************************
* /home/ott/acqu/root/src/MCUserDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/ott/acqu/root/src/MCUserDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMCUserDict();
extern void G__cpp_setup_inheritanceMCUserDict();
extern void G__cpp_setup_typetableMCUserDict();
extern void G__cpp_setup_memvarMCUserDict();
extern void G__cpp_setup_globalMCUserDict();
extern void G__cpp_setup_memfuncMCUserDict();
extern void G__cpp_setup_funcMCUserDict();
extern void G__set_cpp_environmentMCUserDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ott/acqu/root/src/TMCUserGenerator.h"
#include "/home/ott/acqu/root/src/TMCUserParticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MCUserDictLN_TClass;
extern G__linked_taginfo G__MCUserDictLN_TBuffer;
extern G__linked_taginfo G__MCUserDictLN_TMemberInspector;
extern G__linked_taginfo G__MCUserDictLN_TObject;
extern G__linked_taginfo G__MCUserDictLN_TNamed;
extern G__linked_taginfo G__MCUserDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MCUserDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCUserDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MCUserDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCUserDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MCUserDictLN_TParticlePDG;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MCUserDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MCUserDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MCUserDictLN_TRandom;
extern G__linked_taginfo G__MCUserDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MCUserDictLN_TA2System;
extern G__linked_taginfo G__MCUserDictLN_TMCParticle;
extern G__linked_taginfo G__MCUserDictLN_TMCGenerator;
extern G__linked_taginfo G__MCUserDictLN_TMCFoamGenerator;
extern G__linked_taginfo G__MCUserDictLN_TMCUserGenerator;
extern G__linked_taginfo G__MCUserDictLN_TMCUserParticle;

/* STUB derived class for protected member access */
