/********************************************************************
* /home/ott/acqu/root/src/UserDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/ott/acqu/root/src/UserDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableUserDict();
extern void G__cpp_setup_inheritanceUserDict();
extern void G__cpp_setup_typetableUserDict();
extern void G__cpp_setup_memvarUserDict();
extern void G__cpp_setup_globalUserDict();
extern void G__cpp_setup_memfuncUserDict();
extern void G__cpp_setup_funcUserDict();
extern void G__set_cpp_environmentUserDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ott/acqu/root/src/TA2CalArray.h"
#include "/home/ott/acqu/root/src/TA2FPMicro.h"
#include "/home/ott/acqu/root/src/TA2GenericApp.h"
#include "/home/ott/acqu/root/src/TA2MyAnalysis.h"
#include "/home/ott/acqu/root/src/TA2MyCaLib.h"
#include "/home/ott/acqu/root/src/TA2MyCalibration.h"
#include "/home/ott/acqu/root/src/TA2MyClusterCalib.h"
#include "/home/ott/acqu/root/src/TA2MyCrystalBall.h"
#include "/home/ott/acqu/root/src/TA2MyPhysics.h"
#include "/home/ott/acqu/root/src/TA2MyRateEstimation.h"
#include "/home/ott/acqu/root/src/TA2MyTAPS_BaF2PWO.h"
#include "/home/ott/acqu/root/src/TA2MyTAPS.h"
#include "/home/ott/acqu/root/src/TA2PlasticPID.h"
#include "/home/ott/acqu/root/src/TA2PlasticVETO.h"
#include "/home/ott/acqu/root/src/TA2UserAnalysis.h"
#include "/home/ott/acqu/root/src/TA2UserControl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__UserDictLN_TClass;
extern G__linked_taginfo G__UserDictLN_TBuffer;
extern G__linked_taginfo G__UserDictLN_TMemberInspector;
extern G__linked_taginfo G__UserDictLN_TObject;
extern G__linked_taginfo G__UserDictLN_TNamed;
extern G__linked_taginfo G__UserDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__UserDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__UserDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__UserDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_TRandom3;
extern G__linked_taginfo G__UserDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__UserDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_TH1;
extern G__linked_taginfo G__UserDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_TQObject;
extern G__linked_taginfo G__UserDictLN_TApplication;
extern G__linked_taginfo G__UserDictLN_TA2System;
extern G__linked_taginfo G__UserDictLN_TA2Analysis;
extern G__linked_taginfo G__UserDictLN_TAcquRoot;
extern G__linked_taginfo G__UserDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__UserDictLN_TH1F;
extern G__linked_taginfo G__UserDictLN_TGraph;
extern G__linked_taginfo G__UserDictLN_TH2;
extern G__linked_taginfo G__UserDictLN_TCutG;
extern G__linked_taginfo G__UserDictLN_TA2BitPattern;
extern G__linked_taginfo G__UserDictLN_TA2DataManager;
extern G__linked_taginfo G__UserDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__UserDictLN_TH2F;
extern G__linked_taginfo G__UserDictLN_TH3;
extern G__linked_taginfo G__UserDictLN_TA2HistManager;
extern G__linked_taginfo G__UserDictLN_TA2Detector;
extern G__linked_taginfo G__UserDictLN_HitD2A_t;
extern G__linked_taginfo G__UserDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__UserDictLN_TVector3;
extern G__linked_taginfo G__UserDictLN_TA2ClusterDetector;
extern G__linked_taginfo G__UserDictLN_HitCluster_t;
extern G__linked_taginfo G__UserDictLN_TA2CalArray;
extern G__linked_taginfo G__UserDictLN_TA2FPMicro;
extern G__linked_taginfo G__UserDictLN_TLorentzVector;
extern G__linked_taginfo G__UserDictLN_TA2Apparatus;
extern G__linked_taginfo G__UserDictLN_TA2GenericDetector;
extern G__linked_taginfo G__UserDictLN_TA2LongScint;
extern G__linked_taginfo G__UserDictLN_TA2PlasticPID;
extern G__linked_taginfo G__UserDictLN_TA2GenericApp;
extern G__linked_taginfo G__UserDictLN_TOA2DetParticle;
extern G__linked_taginfo G__UserDictLN_TOA2RecParticle;
extern G__linked_taginfo G__UserDictLN_THnSparse;
extern G__linked_taginfo G__UserDictLN_THnSparseTlETArrayFgR;
extern G__linked_taginfo G__UserDictLN_TGraphErrors;
extern G__linked_taginfo G__UserDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_TMVA;
extern G__linked_taginfo G__UserDictLN_maplETStringcOTMVAcLcLTypescLcLEMVAcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLTypescLcLEMVAgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__UserDictLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlEfloatmUcOallocatorlEfloatmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_TMVAcLcLReader;
extern G__linked_taginfo G__UserDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__UserDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserDictLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR;
extern G__linked_taginfo G__UserDictLN_TOMCParticle;
extern G__linked_taginfo G__UserDictLN_TNtupleD;
extern G__linked_taginfo G__UserDictLN_TA2Physics;
extern G__linked_taginfo G__UserDictLN_TA2Ladder;
extern G__linked_taginfo G__UserDictLN_TA2Tagger;
extern G__linked_taginfo G__UserDictLN_TA2MyCrystalBall;
extern G__linked_taginfo G__UserDictLN_ETAPSType;
extern G__linked_taginfo G__UserDictLN_TA2MyTAPS_BaF2PWO;
extern G__linked_taginfo G__UserDictLN_TA2PlasticVETO;
extern G__linked_taginfo G__UserDictLN_TA2MyTAPS;
extern G__linked_taginfo G__UserDictLN_TA2GenericApparatus;
extern G__linked_taginfo G__UserDictLN_CaLibReader_t;
extern G__linked_taginfo G__UserDictLN_TA2MyPhysics;
extern G__linked_taginfo G__UserDictLN_TA2MyAnalysis;
extern G__linked_taginfo G__UserDictLN_TA2MyCaLib;
extern G__linked_taginfo G__UserDictLN_TA2MyCalibration;
extern G__linked_taginfo G__UserDictLN_TA2MyClusterCalib;
extern G__linked_taginfo G__UserDictLN_TA2MyRateEstimation;
extern G__linked_taginfo G__UserDictLN_TA2UserAnalysis;
extern G__linked_taginfo G__UserDictLN_TRint;
extern G__linked_taginfo G__UserDictLN_TA2Control;
extern G__linked_taginfo G__UserDictLN_TA2UserControl;

/* STUB derived class for protected member access */
