/********************************************************************
* /home/acqu/4v6/acqu/AcquDAQ/src/DAQDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/acqu/4v6/acqu/AcquDAQ/src/DAQDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDAQDict();
extern void G__cpp_setup_inheritanceDAQDict();
extern void G__cpp_setup_typetableDAQDict();
extern void G__cpp_setup_memvarDAQDict();
extern void G__cpp_setup_globalDAQDict();
extern void G__cpp_setup_memfuncDAQDict();
extern void G__cpp_setup_funcDAQDict();
extern void G__set_cpp_environmentDAQDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVMEmodule.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMAC_2373.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_SIS3820.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TFBmodule.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQcontrol.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQexperiment.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TFB_Phil10C.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQstore.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMAC_GSI4800.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_GeSiCA.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQguiCtrl.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMAC_4508.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_CATCH_TDC.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQ_SY1527.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TFB_LRS1800.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TFB_STR200.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQsupervise.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_V874.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQ_KPhI686.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMAC_4413SPILL.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQ_V2718.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_CATCH.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TEPICSmodule.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_V792.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_V775.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMAC_4413DAQEnable.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TDAQmodule.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_CBD8210.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMACmodule.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_VUPROM.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TGUIsupervise.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TCAMAC_2323.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_CATCH_TCS.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_KPhSMI.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_V1190.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVME_CATCH_Scaler.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TFB_1821SMI.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/TVirtualModule.h"
#include "/home/acqu/4v6/acqu/AcquDAQ/src/DAQMemMap_t.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DAQDictLN_TClass;
extern G__linked_taginfo G__DAQDictLN_TBuffer;
extern G__linked_taginfo G__DAQDictLN_TMemberInspector;
extern G__linked_taginfo G__DAQDictLN_TObject;
extern G__linked_taginfo G__DAQDictLN_TNamed;
extern G__linked_taginfo G__DAQDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DAQDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DAQDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DAQDictLN_TList;
extern G__linked_taginfo G__DAQDictLN_TTimer;
extern G__linked_taginfo G__DAQDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DAQDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DAQDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DAQDictLN_TCanvas;
extern G__linked_taginfo G__DAQDictLN_ARFile_t;
extern G__linked_taginfo G__DAQDictLN_ARSocket_t;
extern G__linked_taginfo G__DAQDictLN_DAQMemMap_t;
extern G__linked_taginfo G__DAQDictLN_TA2System;
extern G__linked_taginfo G__DAQDictLN_TDAQmodule;
extern G__linked_taginfo G__DAQDictLN_TDAQcontrol;
extern G__linked_taginfo G__DAQDictLN_TThread;
extern G__linked_taginfo G__DAQDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__DAQDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DAQDictLN_TQObject;
extern G__linked_taginfo G__DAQDictLN_ModuleInfo_t;
extern G__linked_taginfo G__DAQDictLN_TA2RingBuffer;
extern G__linked_taginfo G__DAQDictLN_ModuleInfoMk2_t;
extern G__linked_taginfo G__DAQDictLN_TControlBar;
extern G__linked_taginfo G__DAQDictLN_TDAQguiCtrl;
extern G__linked_taginfo G__DAQDictLN_TDAQexperiment;
extern G__linked_taginfo G__DAQDictLN_TDAQsupervise;
extern G__linked_taginfo G__DAQDictLN_TGUIsupervise;
extern G__linked_taginfo G__DAQDictLN_TDAQstore;
extern G__linked_taginfo G__DAQDictLN_TAcquRoot;
extern G__linked_taginfo G__DAQDictLN_VMEreg_t;
extern G__linked_taginfo G__DAQDictLN_TVMEmodule;
extern G__linked_taginfo G__DAQDictLN_TCAMACmodule;
extern G__linked_taginfo G__DAQDictLN_TCAMAC_2373;
extern G__linked_taginfo G__DAQDictLN_TVME_SIS3820;
extern G__linked_taginfo G__DAQDictLN_TFB_1821SMI;
extern G__linked_taginfo G__DAQDictLN_TFBmodule;
extern G__linked_taginfo G__DAQDictLN_TFB_Phil10C;
extern G__linked_taginfo G__DAQDictLN_TCAMAC_GSI4800;
extern G__linked_taginfo G__DAQDictLN_CatchWrt_t;
extern G__linked_taginfo G__DAQDictLN_TVME_CATCH;
extern G__linked_taginfo G__DAQDictLN_TVME_GeSiCA;
extern G__linked_taginfo G__DAQDictLN_TGWindow;
extern G__linked_taginfo G__DAQDictLN_TGFont;
extern G__linked_taginfo G__DAQDictLN_TGObject;
extern G__linked_taginfo G__DAQDictLN_TGFrame;
extern G__linked_taginfo G__DAQDictLN_TGCompositeFrame;
extern G__linked_taginfo G__DAQDictLN_TGTextButton;
extern G__linked_taginfo G__DAQDictLN_TGVerticalFrame;
extern G__linked_taginfo G__DAQDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__DAQDictLN_TGMainFrame;
extern G__linked_taginfo G__DAQDictLN_TGGroupFrame;
extern G__linked_taginfo G__DAQDictLN_TGCheckButton;
extern G__linked_taginfo G__DAQDictLN_TGTextEntry;
extern G__linked_taginfo G__DAQDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__DAQDictLN_TGNumberEntry;
extern G__linked_taginfo G__DAQDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__DAQDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DAQDictLN_TGTextView;
extern G__linked_taginfo G__DAQDictLN_TH1F;
extern G__linked_taginfo G__DAQDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DAQDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DAQDictLN_TCAMAC_4508;
extern G__linked_taginfo G__DAQDictLN_F1Data_t;
extern G__linked_taginfo G__DAQDictLN_TVME_CATCH_TDC;
extern G__linked_taginfo G__DAQDictLN_HV_1932_t;
extern G__linked_taginfo G__DAQDictLN_TDAQ_SY1527;
extern G__linked_taginfo G__DAQDictLN_TFB_LRS1800;
extern G__linked_taginfo G__DAQDictLN_TFB_STR200;
extern G__linked_taginfo G__DAQDictLN_TVME_V874;
extern G__linked_taginfo G__DAQDictLN_TDAQ_KPhI686;
extern G__linked_taginfo G__DAQDictLN_TCAMAC_4413SPILL;
extern G__linked_taginfo G__DAQDictLN_TDAQ_V2718;
extern G__linked_taginfo G__DAQDictLN_TEPICSmodule;
extern G__linked_taginfo G__DAQDictLN_TVME_V792;
extern G__linked_taginfo G__DAQDictLN_TVME_V775;
extern G__linked_taginfo G__DAQDictLN_TCAMAC_4413DAQEnable;
extern G__linked_taginfo G__DAQDictLN_TVME_CBD8210;
extern G__linked_taginfo G__DAQDictLN_TVME_VUPROM;
extern G__linked_taginfo G__DAQDictLN_TCAMAC_2323;
extern G__linked_taginfo G__DAQDictLN_TVME_CATCH_TCS;
extern G__linked_taginfo G__DAQDictLN_TVME_KPhSMI;
extern G__linked_taginfo G__DAQDictLN_TVME_V1190;
extern G__linked_taginfo G__DAQDictLN_TVME_CATCH_Scaler;
extern G__linked_taginfo G__DAQDictLN_TRandom;
extern G__linked_taginfo G__DAQDictLN_TVirtualModule;

/* STUB derived class for protected member access */
